### ISSUE TITLE
可以分享api的制作方法吗

### ISSUE THREAD

**Issue by Ryousamac** [pcrbot/ai_setu#1]
很抱歉提一个与项目本身无关的issue
我想用自己机器的sd开个接口(已穿透)但是api部分不会写
想偷份现成的_(:зゝ∠)_

**Comment by sanshanya** [comment]
添加启动参数

- 端口转发
参数 --listen 使服务器监听网络连接。
- 监听端口
添加参数 --port xxxx 使服务器监听特定端口。
默认端口为 7860
- 使用 --api 参数运行程序，在浏览器访问 {输出的网址}/docs 就可以查看到 WebUi 的 [Api](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/master/modules/api) 文档
推荐启动参数--xformers --opt-split-attention --opt-channelslast --api --listen --port 7860

**Comment by Ryousamac** [comment]
谢谢，可以使用了，才发现sd内置fastapi。
