### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by YinBuLiao** [pcrbot/ai_setu#12]
![6LW`PS{$(2 T@7D2ENUYP65](https://user-images.githubusercontent.com/35324248/203922976-45c94efa-adbe-4ec3-b441-350fc262ca6c.png)

**Comment by sanshanya** [comment]
请问是在什么情况时触发的?
触发稳定嘛?
你有改动过代码嘛?

**Comment by YinBuLiao** [comment]
SD绘图 没有改动代码

**Comment by sanshanya** [comment]
> SD绘图 没有改动代码

可能是你没有获取翻译apikey和id但是开启了翻译功能导致，关闭翻译功能后试试，或者tag选用英文

**Comment by YinBuLiao** [comment]
好的 我试试

**Comment by YinBuLiao** [comment]
![image](https://user-images.githubusercontent.com/35324248/204099925-0388bce3-24a7-4658-b30c-cbb837e3a0bf.png)
以图绘图 好几分钟了没反应后台也没报错请问这是正常的吗
47开始到现在都还没返图
