### ISSUE TITLE
安装插件的时候遇到了一些问题

### ISSUE THREAD

**Issue by Jacky117** [pcrbot/ai_setu#15]
之前用电线佬的ai绘图插件是没问题的，但这次根据步骤安装修改后发现连trigger也没有了，想请问一下可能是什么问题，不知道是不是配置文件的问题。目前配置文件就修改了路路佬的api以及有道和百度翻译的api，其他都没动，所以暂时没弄清是哪里的问题

**Comment by sanshanya** [comment]
Q群711462207内询问
