### ISSUE TITLE
内置的sd API是不是挂了

### ISSUE THREAD

**Issue by WindraiteLesd** [pcrbot/ai_setu#19]
一直连不上

**Comment by xi-yue-233** [comment]
我也是遇到这个问题

**Comment by Agnes4m** [comment]
![image](https://user-images.githubusercontent.com/70925546/208022901-ce3a3990-9d75-4803-b4f2-aafc3ee9a6bb.png)

**Comment by SanaChitose** [comment]
同样的问题
