### ISSUE TITLE
这个插件可以window装吗  我想装在真寻上

### ISSUE THREAD

**Issue by 1103859909** [pcrbot/ai_setu#2]

**Comment by sanshanya** [comment]
可以的

**Comment by 1103859909** [comment]
装在真寻bot上没反应  也没报错

![image](https://user-images.githubusercontent.com/107859647/202909352-c00c5889-1087-465e-bc28-2fe4cd552302.png)
![image](https://user-images.githubusercontent.com/107859647/202909380-c28aae93-7d51-4429-91cc-ec82a24b5f9c.png)
![image](https://user-images.githubusercontent.com/107859647/202909432-5a057b54-5fa1-4b64-a18b-c529715f8b5e.png)
