### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by MiuClips-F** [pcrbot/ai_setu#20]
![image](https://user-images.githubusercontent.com/28744408/208342097-fd0e2ee3-ecaf-42d1-9039-57d8c1559893.png)
请教一下大佬，现在以图绘图会报错，其他命令都正常，可能是什么原因导致的

**Comment by Agnes4m** [comment]
路路的api似乎就是不能以图绘图

**Comment by MiuClips-F** [comment]
> 请教一下大佬，现在以图绘图会报错，其他命令都正常，可能是什么原因导致的

了解了，看了下源码发现以图绘图用的好像都是sd的api，感谢回复。
