### ISSUE TITLE
帮助;如何获取SD的token

### ISSUE THREAD

**Issue by Agnes4m** [pcrbot/ai_setu#5]
如题，百度搜过找不到方法

**Comment by 1529960009** [comment]
你说本地为web-ui么，在启动参数后面加一个--api

**Comment by miragekc** [comment]
我也没找到方法，自建的怎样获取token，从网页端已经是可以直接访问了呢

**Comment by Agnes4m** [comment]
> 你说本地为web-ui么，在启动参数后面加一个--api

网页端的token怎么获取捏

**Comment by Agnes4m** [comment]
> 我也没找到方法，自建的怎样获取token，从网页端已经是可以直接访问了呢

问问大佬网页端的token是怎么获取的orz，我获取总是Method Not Allowed
![image](https://user-images.githubusercontent.com/70925546/204138555-189a3776-bead-4803-a65e-045678d5c10f.png)

**Comment by sanshanya** [comment]
自建只要自己没有设置就不需要token

**Comment by Agnes4m** [comment]
不是自建，是sd网页端（api）的token我不清楚应该如何获取，麻烦大佬了

> 自建只要自己没有设置就不需要token

**Comment by sanshanya** [comment]
sb webui自带的api是不需要token的,如果需要token只能问sd webui的主人
