### ISSUE TITLE
pip依赖安装失败

### ISSUE THREAD

**Issue by chumeng666** [pcrbot/ai_setu#7]
arm设备其他依赖都装成功了，就安装pyahocorasick的时候失败了

**Comment by chumeng666** [comment]
这个是报错
root@localhost:~/HoshinoBot/hoshino/modules/ai_setu# pip install pyahocorasick
Looking in indexes: https://mirrors.bfsu.edu.cn/pypi/web/simple
Collecting pyahocorasick
  Using cached https://mirrors.bfsu.edu.cn/pypi/web/packages/8a/ba/9a870b3ad3ff5fa4a4d8d5905ae1fcbf02f4181cde85d91a2279ad7fdd81/pyahocorasick-1.4.4.tar.gz (95 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pyahocorasick
  Building wheel for pyahocorasick (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      /usr/local/lib/python3.8/dist-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running bdist_wheel
      running build
      running build_ext
      building 'ahocorasick' extension
      creating build
      creating build/temp.linux-aarch64-cpython-38
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DAHOCORASICK_UNICODE= -I/usr/include/python3.8 -c pyahocorasick.c -o build/temp.linux-aarch64-cpython-38/pyahocorasick.o
      In file included from pyahocorasick.c:13:0:
      common.h:15:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyahocorasick
  Running setup.py clean for pyahocorasick
Failed to build pyahocorasick
Installing collected packages: pyahocorasick
  Running setup.py install for pyahocorasick ... error
  error: subprocess-exited-with-error

  × Running setup.py install for pyahocorasick did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      /usr/local/lib/python3.8/dist-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
        warnings.warn(msg, warning_class)
      running install
      /usr/local/lib/python3.8/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'ahocorasick' extension
      creating build
      creating build/temp.linux-aarch64-cpython-38
      aarch64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DAHOCORASICK_UNICODE= -I/usr/include/python3.8 -c pyahocorasick.c -o build/temp.linux-aarch64-cpython-38/pyahocorasick.o
      In file included from pyahocorasick.c:13:0:
      common.h:15:10: fatal error: Python.h: No such file or directory
       #include <Python.h>
                ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyahocorasick

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by sanshanya** [comment]
可以尝试https://github.com/pcrbot/ai_setu/issues/4
或者去百度一下
`fatal error: Python.h: No such file or directory`
