### ISSUE TITLE
模型切换BUG,SD控制台显示切换失败，机器人显示切换成功,

### ISSUE THREAD

**Issue by 1529960009** [pcrbot/ai_setu#8]
![QQ截图20221122023805](https://user-images.githubusercontent.com/45947734/203134561-c79da444-82eb-48fe-841c-592e7f61d680.png)
![QQ截图20221122023820](https://user-images.githubusercontent.com/45947734/203134574-fea9a48d-74d7-4ce6-b42a-2eb99d6c782d.png)
模型切换失败
切换后，SD网页中的checkpoint为空
![QQ截图20221122024122](https://user-images.githubusercontent.com/45947734/203134993-cee02d4e-1d7e-4ab5-b7d5-1b56018a36de.png)

**Comment by 1529960009** [comment]
![QQ截图20221122024406](https://user-images.githubusercontent.com/45947734/203135530-ef2a7b40-d6ba-4bf8-953f-5f9c74258a0a.png)
config中的配置

**Comment by sanshanya** [comment]
模型应该有ckpt的后缀哦
