### ISSUE TITLE
路路佬的api好像用不了了

### ISSUE THREAD

**Issue by SanaChitose** [pcrbot/ai_setu#9]
这两天换过很多个token，一直提示token冷却中，在电线佬那边提示就是index error，我postman试了一下也没有数据过来，已经加群验证过token了，是我使用的姿势不对吗？
SD绘图没有问题

**Comment by sanshanya** [comment]
路路佬的友情api由于友情值不足,不太稳定

**Comment by SanaChitose** [comment]
> 路路佬的友情api由于友情值不足,不太稳定

那么有充值友情的办法吗？希望指点

**Comment by sanshanya** [comment]
这事只能问本人了,我已经基本只用本地了

**Comment by dfmjndm** [comment]
感觉是插件问题，使用以下代码直接调用是可以的，但是这边插件会显示token冷却中
@sv.on_prefix(('ai绘图'))
async def gen_pic(bot, ev: CQEvent):
    try:
        await bot.send(ev, f"正在生成，请稍后...", at_sender=True)
        text = ev.message.extract_plain_text()
        get_url = word2img_url + text + token
        # image = await aiorequests.get(get_url)
        res = await aiorequests.get(get_url)
        image = await res.content
        load_data = json.loads(re.findall('{"steps".+?}', str(image))[0])
        image_b64 = 'base64://' + str(base64.b64encode(image).decode())
        mes = f"[CQ:image,file={image_b64}]\n"
        mes += f'seed:{load_data["seed"]}   '
        mes += f'scale:{load_data["scale"]}'
        await bot.send(ev, mes, at_sender=True)
    except:
        await bot.send(ev, "生成失败…")
